# Input Parameters for Laplace Solver

# Case Name
NAME = numerical_solution  # Standard case according to Challenge

# Spatial Discretization
N = 60
DOMAIN = 0, 1, 0, 1  # Domain: x_min, x_max, y_min, y_max

# Solver settings
MAXITER   = 100000  # Number of iterations
TOLERANCE = 1e-6    # Convergence Criterion